tipo = input('Digite algo : ')
print ('O tipo primitivo disso aí é', type(tipo))
print(' ')
print('Só tem espaços ? ', tipo.isspace())
print('É um número ? ', tipo.isnumeric())
print('É alfabético ? ', tipo.isalpha())
print('É alfanumérico ? ', tipo.isalnum())
print('Esatá em maiúscula ? ', tipo.isupper())
print('Está em minúscula ? ', tipo.islower())
print('Está capitalizada', tipo.istitle())
